services:
  getth-cms:
    container_name: "getth-cms"
    build: ./
    ports:
      - "4000"
    volumes:
      - ./:/app
  caddy:
    container_name: "caddy"
    image: caddy:2-alpine
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"
      - "443:443/udp"
    volumes:
      - $PWD/.docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/.docker/caddy/data:/data
      - $PWD/.docker/caddy/config:/config
    extra_hosts:                                                                                                                                                                                                   
      - "host.docker.internal:host-gateway" 
# volumes:
#   caddy_data:
#     external: true
#   caddy_config:

